name: Master

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Build Wheels - Linux
        if: startsWith(matrix.os, 'ubuntu')
        env:
          PYTHON_VERSION: python${{ matrix.python-version }}
        run: |
          docker build . -t maturin:latest
          docker run --rm -v $(pwd):/io maturin:latest sh -c "source ~/.cargo/env && maturin build -i $PYTHON_VERSION --release --out wheels"

      - name: Build Wheels - Non-Linux
        if: startsWith(matrix.os, 'windows') || startsWith(matrix.os, 'macos')
        run: |
          pip install maturin
          maturin build -i python --release --out wheels

      - name: Install wheel
        run: pip install murmurhash2 --no-index --find-links wheels

      - name: Python UnitTest
        run: |
          pip install pytest
          pytest -v tests/
